// Code generated by Fabrica. DO NOT EDIT manually.
// This is a stub file created during init to prevent import errors.
// It will be replaced when you run 'fabrica generate --storage'

package storage

import (
	"fmt"
	"os"
)

// InitFileBackend initializes the file storage backend
func InitFileBackend(dataDir string) error {
	if _, err := os.Stat(dataDir); os.IsNotExist(err) {
		if err := os.MkdirAll(dataDir, 0755); err != nil {
			return fmt.Errorf("failed to create data directory: %w", err)
		}
	}
	return nil
}

// Placeholder to prevent import errors - will be replaced by generated code
