// Code generated by Fabrica. DO NOT EDIT.
package main

import (
	"github.com/openchami/fabrica/pkg/events"
)

// InitializeEventBus initializes the event bus (deprecated, use NewInMemoryEventBus instead)
func InitializeEventBus() events.EventBus {
	return events.NewInMemoryEventBus(1000, 10)
}
