// Code generated by Fabrica. DO NOT EDIT.
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
)

// RegisterGeneratedRoutes registers all generated API routes
func RegisterGeneratedRoutes(r *chi.Mux) {
	// This service is a middleware reconciler with no resources
	// Routes will be added here when resources are defined
}

// registerResourcePrefixes registers resource type prefixes for UID generation
func registerResourcePrefixes() error {
	// This service has no resources
	return nil
}

// GlobalEventBus holds the global event bus instance
var GlobalEventBus events.EventBus
